name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [x1s]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Upload .zip to Gofile with token
        run: |
          # Set values
          FILE="${{ steps.zipinfo.outputs.zipfile }}"
          TOKEN="${{ secrets.GOFILE_TOKEN }}"
          ENDPOINT="https://upload.gofile.io/uploadFile"  # change to a regional one if desired

          # Prepare curl command
          RESPONSE=$(curl -s -F "file=@$FILE" -F "token=$TOKEN" "$ENDPOINT")

          # Show result
          echo "$RESPONSE" > gofile_response.json
          echo "Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'
