name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [x1s]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Upload .zip to Gofile with token
        run: |
          # Set values
          ZIP_FILE=$(find out -name "*.zip" | head -n 1)
          TOKEN="${{ secrets.GOFILE_TOKEN }}"
          ENDPOINT="https://upload.gofile.io/uploadFile"

          # Prepare curl command
          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=bb4ebab0-1ef3-4925-a9f5-5b07a42a15a1" "$ENDPOINT")

          # Show result
          echo "Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'
